// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSaGy9y6LcKMnijNDM0K_3_MXZS1zg86k',
    appId: '1:770106906255:android:fe9c886f32bcec8d1b42fa',
    messagingSenderId: '770106906255',
    projectId: 'cardiotwin-ff729',
    storageBucket: 'cardiotwin-ff729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoE777wIDl67UtxKCy_nEmr8BQVLPGl3U',
    appId: '1:770106906255:ios:278f375b52f3c1701b42fa',
    messagingSenderId: '770106906255',
    projectId: 'cardiotwin-ff729',
    storageBucket: 'cardiotwin-ff729.firebasestorage.app',
    androidClientId: '770106906255-bktn1ucnasrer25tbis67sv99stpgecg.apps.googleusercontent.com',
    iosClientId: '770106906255-q9duqelf97gia2di93e6abpv0a7hhvoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardiotwin',
  );

}